language: python

install:
  - pip install codecov "tox<2.0"

script:
  - tox
  - tox -e combine py34 py33 pypy py27 py26

after_success:
  - mv tests/.coverage .
  - codecov || true

env:
  - BROKER: sqlite
  - BROKER: mysql
  - BROKER: postgres
  - BROKER: redis
  - BROKER: redis_sock,/tmp/redis.sock

services:
  - redis-server

before_script:
  - echo -e "daemonize yes\nunixsocket /tmp/redis.sock\nport 0" |redis-server -
  - mysql -u root -e 'CREATE DATABASE flask_celery_helper_test;'
  - mysql -u root -e 'GRANT ALL PRIVILEGES ON flask_celery_helper_test.* TO "user"@"localhost" IDENTIFIED BY "pass";'
  - psql -U postgres -c 'CREATE DATABASE flask_celery_helper_test;'
  - psql -U postgres -c "CREATE USER user1 WITH PASSWORD 'pass';"
  - psql -U postgres -c 'GRANT ALL PRIVILEGES ON DATABASE flask_celery_helper_test TO user1;'
