language: python

python:
  - 2.6
  - 2.7
  - pypy
  - 3.3
  - 3.4

install:
  - python -c 'import setup; print(setup.REQUIRES_PIP)' |xargs pip install
  - pip install robpol86-codecov
  - pip install .

script:
  - python setup.py test && codecov  # SQLAlchemy SQLite
  - BROKER=redis python setup.py test && codecov
  - BROKER=redis_sock,/tmp/redis.sock python setup.py test && codecov
  #- BROKER=mongo python setup.py test && codecov
  #- BROKER=couch python setup.py test && codecov
  #- BROKER=beanstalk python setup.py test && codecov
  #- BROKER=iron python setup.py test && codecov
  - BROKER=mysql python setup.py test && codecov
  - BROKER=postgres python setup.py test && codecov

before_script:
  - echo -e "daemonize yes\nunixsocket /tmp/redis.sock\nport 0" |redis-server -
  - mysql -u root -e 'CREATE DATABASE flask_celery_helper_test;'
  - mysql -u root -e 'GRANT ALL PRIVILEGES ON flask_celery_helper_test.* TO "user"@"localhost" IDENTIFIED BY "pass";'
  - psql -U postgres -c 'CREATE DATABASE flask_celery_helper_test;'
  - psql -U postgres -c "CREATE USER user1 WITH PASSWORD 'pass';"
  - psql -U postgres -c 'GRANT ALL PRIVILEGES ON DATABASE flask_celery_helper_test TO user1;'

services:
  - redis-server
  - mongodb
  - couchdb
