language: python

python:
  - 2.6
  - 2.7
  - pypy
  - 3.3
  - 3.4

install:
  - python -c 'import setup; print(setup.REQUIRES_PIP)' |xargs pip install
  - pip install robpol86-codecov
  - pip install .

script:
  #- python setup.py test  # SQLAlchemy SQLite
  #- BROKER=rabbit python setup.py test
  - BROKER=redis python setup.py test
  #- BROKER=redis_sock python setup.py test
  #- BROKER=mongo python setup.py test
  #- BROKER=couch python setup.py test
  #- BROKER=beanstalk python setup.py test
  #- BROKER=iron python setup.py test
  #- BROKER=mysql python setup.py test
  #- BROKER=postgres python setup.py test

after_success: codecov

services:
  - redis-server
  - rabbitmq
  - mongodb
  - couchdb
